Repository reviewdog/action-eslint, pull requests merged in 2020-05, with the labels that each got.

#27 Added new reviewdog flags introduced by reviewdog v0.10.0
  README.md
  action.yml
  entrypoint.sh
Labels: bump:minor

#28 Add missing word to workdir input description
  README.md
  action.yml
Labels: documentation

#31 Provide a default Github token
  .github/workflows/reviewdog.yml
  README.md
  action.yml
Labels: bump:minor, documentation, enhancement

#30 feat(action-options): add tool_name option for reviewdog reporter
  action.yml
  entrypoint.sh
Labels: bump:minor
