Repository reviewdog/action-eslint, pull requests merged in 2020-10, with the labels that each got.

#43 Support suggestions by introducing rdformat
  .eslintrc.js
  .github/workflows/test.yml
  Dockerfile
  README.md
  entrypoint.sh
  eslint-formatter-rdjson/index.js
  eslint-formatter-rdjson/package.json
  eslint-formatter-rdjson/test-update-ok-file.sh
  eslint-formatter-rdjson/test.sh
  eslint-formatter-rdjson/testdata/.gitignore
  eslint-formatter-rdjson/testdata/result.ok
  package-lock.json
  package.json
  test-subproject/.eslintrc.js
  testdata/test.js
Labels: bump:minor

#50 fix error when source not exist
  eslint-formatter-rdjson/index.js
Labels: bump:patch, hacktoberfest-accepted

#53 Fix Cannot read property 'docs' of undefined
  .github/workflows/reviewdog.yml
  eslint-formatter-rdjson/index.js
  eslint-formatter-rdjson/package.json
  test-subproject/sub-testdata/test.js
Labels: bump:minor

#54 Fix reporter input and change the default reporter for suggestion
  README.md
  action.yml
  entrypoint.sh
  test-subproject/sub-testdata/test.js
Labels: bump:patch

#55 Add legacy-peer-deps option for peer dependencies conflicts
  entrypoint.sh
Labels: bump:patch
